name: Auto Add Issues to Project

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1
        with:
          project-url: https://github.com/ORG_OR_USER/REPO/projects/PROJECT_ID
          github-token: ${{ secrets.GITHUB_TOKEN }}
