name: Full CI/CD Pipeline with S3 Deployment

on:
  push:
    branches:
    - main

jobs:
# 1. Matrix Testing
  test:
    name: Matrix Node.js Testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm run test:unit
  # 2. Security Scanning
  security:
    name: Security Scan
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Static Code Analysis (SAST)
        run: npm run lint

      - name: Dependency Vulnerability Scan (SCA)
        run: npm audit --audit-level=high

      - name: Enforce Quality Gate
        run: |
          npm audit --json > audit.json
          SEVERITIES=$(jq '.metadata.vulnerabilities | to_entries | map(select(.value > 0 and .key != "low")) | length' audit.json)
          if [ "$SEVERITIES" -gt 0 ]; then
            echo "❌ Security vulnerabilities found."
            exit 1
          fi       
  
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'
